/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    orders: Order;
    coupons: Coupon;
    media: Media;
    boxes: Box;
    categories: Category;
    clients: Client;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    boxes: BoxesSelect<false> | BoxesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    minimumStock: MinimumStock;
    metro: Metro;
  };
  globalsSelect: {
    minimumStock: MinimumStockSelect<false> | MinimumStockSelect<true>;
    metro: MetroSelect<false> | MetroSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstname?: string | null;
  role?: ('admin' | 'api') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  slug?: string | null;
  cover: string | Media;
  highlighted?: boolean | null;
  texture?: (string | null) | Media;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  stock: number;
  sales?: number | null;
  isCustom?: boolean | null;
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  altText: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  items?:
    | {
        product: string | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  interactionHistory?:
    | {
        interactionType?: string | null;
        interactionSummary?: string | null;
        interactionDate?: string | null;
        id?: string | null;
      }[]
    | null;
  subscriptionStockNotification?: boolean | null;
  productCustomizationOptions?:
    | {
        tipoDeSticker?: ('paraMetro' | 'paraTarjetaDeDebito' | 'cortePersonalizado') | null;
        id?: string | null;
      }[]
    | null;
  postSaleFeedback?: string | null;
  coupon?: (string | null) | Coupon;
  payment?: {
    jsonpayment?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    paymentMethod?: string | null;
    paymentId?: string | null;
    paymentStatus?: string | null;
    paymentDate?: string | null;
    jsonPayment?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  shipping?: {
    shipment?: {
      status?: string | null;
      id?: string | null;
      provider?: string | null;
      service_level_name?: string | null;
      service_level_code?: string | null;
      days?: number | null;
      total_pricing?: number | null;
      label?: {
        id?: string | null;
        tracking_number?: string | null;
        label_url?: string | null;
        tracking_url_provider?: string | null;
        status?: string | null;
        tracking_status?: string | null;
        rate_id?: number | null;
      };
    };
    shippingMethod?: ('metro' | 'domicilio') | null;
    lineAddress?: string | null;
    references?: string | null;
    interiorNumber?: string | null;
    address?:
      | (
          | {
              street: string;
              exteriorNumber: string;
              interiorNumber?: string | null;
              colony: string;
              zipCode: string;
              city: string;
              state: string;
              references: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'address';
            }
          | {
              metroStation: 'barrancaDelMuerto' | 'divisionDelNorte';
              id?: string | null;
              blockName?: string | null;
              blockType: 'metroStation';
            }
        )[]
      | null;
  };
  id: number;
  subtotal?: number | null;
  total?: number | null;
  paid?: boolean | null;
  status?:
    | (
        | 'unfinished'
        | 'awaitingPayment'
        | 'awaitingPrinting'
        | 'awaitingPrintDelivery'
        | 'awaitingShipping'
        | 'awaitingDelivery'
        | 'delivered'
        | 'cancelled'
        | 'refunded'
        | 'error'
      )
    | null;
  deliveryDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  type: 'percentage' | 'absolute';
  discount: number;
  uses: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boxes".
 */
export interface Box {
  id: string;
  slug?: string | null;
  cover: string | Media;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  stock: number;
  sales?: number | null;
  isVisible?: boolean | null;
  products: (string | Product)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  slug?: string | null;
  cover: string | Media;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isVisible?: boolean | null;
  products: (string | Product)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  name?: string | null;
  phone: string;
  email?: string | null;
  conversations?:
    | {
        chatId?: string | null;
        threadId?: string | null;
        lastMessage?: string | null;
        messages?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  order?: (number | null) | Order;
  addresses?:
    | {
        address?:
          | (
              | {
                  street: string;
                  exteriorNumber: string;
                  interiorNumber?: string | null;
                  colony: string;
                  zipCode: string;
                  city: string;
                  state: string;
                  references: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'address';
                }
              | {
                  metroStation: 'zocalo' | 'divisionDelNorte' | 'etiopia' | 'allende' | 'bellasArtes' | 'hidalgo';
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'metroStation';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'boxes';
        value: string | Box;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstname?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  cover?: T;
  highlighted?: T;
  texture?: T;
  name?: T;
  description?: T;
  price?: T;
  stock?: T;
  sales?: T;
  isCustom?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  name?: T;
  phone?: T;
  email?: T;
  interactionHistory?:
    | T
    | {
        interactionType?: T;
        interactionSummary?: T;
        interactionDate?: T;
        id?: T;
      };
  subscriptionStockNotification?: T;
  productCustomizationOptions?:
    | T
    | {
        tipoDeSticker?: T;
        id?: T;
      };
  postSaleFeedback?: T;
  coupon?: T;
  payment?:
    | T
    | {
        jsonpayment?: T;
        paymentMethod?: T;
        paymentId?: T;
        paymentStatus?: T;
        paymentDate?: T;
        jsonPayment?: T;
      };
  shipping?:
    | T
    | {
        shipment?:
          | T
          | {
              status?: T;
              id?: T;
              provider?: T;
              service_level_name?: T;
              service_level_code?: T;
              days?: T;
              total_pricing?: T;
              label?:
                | T
                | {
                    id?: T;
                    tracking_number?: T;
                    label_url?: T;
                    tracking_url_provider?: T;
                    status?: T;
                    tracking_status?: T;
                    rate_id?: T;
                  };
            };
        shippingMethod?: T;
        lineAddress?: T;
        references?: T;
        interiorNumber?: T;
        address?:
          | T
          | {
              address?:
                | T
                | {
                    street?: T;
                    exteriorNumber?: T;
                    interiorNumber?: T;
                    colony?: T;
                    zipCode?: T;
                    city?: T;
                    state?: T;
                    references?: T;
                    id?: T;
                    blockName?: T;
                  };
              metroStation?:
                | T
                | {
                    metroStation?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  id?: T;
  subtotal?: T;
  total?: T;
  paid?: T;
  status?: T;
  deliveryDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  id?: T;
  type?: T;
  discount?: T;
  uses?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boxes_select".
 */
export interface BoxesSelect<T extends boolean = true> {
  slug?: T;
  cover?: T;
  name?: T;
  description?: T;
  price?: T;
  stock?: T;
  sales?: T;
  isVisible?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  cover?: T;
  name?: T;
  description?: T;
  isVisible?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  conversations?:
    | T
    | {
        chatId?: T;
        threadId?: T;
        lastMessage?: T;
        messages?: T;
        id?: T;
      };
  order?: T;
  addresses?:
    | T
    | {
        address?:
          | T
          | {
              address?:
                | T
                | {
                    street?: T;
                    exteriorNumber?: T;
                    interiorNumber?: T;
                    colony?: T;
                    zipCode?: T;
                    city?: T;
                    state?: T;
                    references?: T;
                    id?: T;
                    blockName?: T;
                  };
              metroStation?:
                | T
                | {
                    metroStation?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * El número mínimo de stock para enviar un mensaje de telegram
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "minimumStock".
 */
export interface MinimumStock {
  id: string;
  minimumStock: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configuración de entrega en metro.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metro".
 */
export interface Metro {
  id: string;
  metroStations?:
    | {
        name: string;
        line: string;
        id?: string | null;
        active: boolean;
        image: string | Media;
      }[]
    | null;
  metroPrice: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "minimumStock_select".
 */
export interface MinimumStockSelect<T extends boolean = true> {
  minimumStock?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metro_select".
 */
export interface MetroSelect<T extends boolean = true> {
  metroStations?:
    | T
    | {
        name?: T;
        line?: T;
        id?: T;
        active?: T;
        image?: T;
      };
  metroPrice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}